#FORMULARIOS_SENAI_SAUDE\backend\migrations\versions\f0745692056c_criação_inicial_do_schema.py
"""Criação inicial do schema

Revision ID: f0745692056c
Revises: 
Create Date: 2025-08-07 09:10:53.541033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0745692056c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campos', 'formulario_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('campos', 'propriedades')
    op.drop_column('campos', 'ordem')
    op.alter_column('respostas', 'formulario_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('respostas', 'formulario_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('campos', sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('campos', sa.Column('propriedades', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('campos', 'formulario_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
